language: node_js
node_js:
  - node
cache: npm
env:
  global:
script:
  - rm -rf $TRAVIS_BUILD_DIR/build
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: scp -r $TRAVIS_BUILD_DIR/build/* ${SSH_USER}@${SSH_HOST}:/${DEPLOY_DIR}
  on:
    branch: master
  local_dir: build
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_63cbc52e9149_key -iv $encrypted_63cbc52e9149_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa2
  - ssh-add .travis/id_rsa2
  - echo -e "Host ${SSH_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
