language: node_js
node_js:
  - node
cache: npm
env:
  global:
    - secure: 07XMITs4Jh7wxs4/UZBECYArbBmNJlpKol1IWq5ZLKLIbSdxKvyfkyx34g+xgp0aFETpiI8tiUjpoY+WMlq1oAiAdes4yN+lwhxtKsgyo9TUezUX86izbobvkozYl5ZnQFVvs43+FIQ4lqJwiu5l6B/pxTZtH4sRYCrXkDAyOCm6REz77AX6GvRh0J/aFsO4NOcNhcaRDoxs8wdQ8AOjSrhlziHG/Eli+aaVFkO79NYY9ZL/tIuKqyCwy0tDoT3PFDbD06fphWn1uEhR65oeblUwqqSwFfe4GyxJP+uIIAcDh1Qqv4gVW/pgZi9rfW5+/he28iTsI5qGmqyEq7IEEkDiO4opeKNDhVnffsmz3f5oSRbIrJFRZWt+b3iXXOthGQym9WJCcEudSLYiwAnG5Q9Opw4IYooPee6lkUlrqTZODgzWdniEO0NuQWeHc4AV6Y8dJ85bclee2y9rebslNj+Si07u0LG4c34f7g4RykfIrnoXWoPF0TiMXd2fXuynm0bFZaOg1Wdbq1veoL+bCHdGcXqIQVEZOiKNW7xtoarEDc5aFZCIBa6+g6OzpfdTRc9CTpFtXYLdyI89H275KuyNZ9NEIiZH910DT7GsABl54hYKbE82gPmiXgtOeNiagI7064vqioIVZhEvuWJwmw0CPwSSUuWEBOFXCl52cYY=
    - secure: amYg3sGbnLuwexzaIQbm1XL5pdW9Ee6ED41Z/5Bo8uYmu0U4xJJK9E6/oaHFo7D3H0K/Q7isr0KvocEfzK+QfJoWao6A5BQ0AtlN/KRnx6BWYCHHbWVySf+dHG9OKJ6CsAka/yu5FmFED9CdlaPNoO1Wo64EwxTwqZMoJYfMwnZF9olCTs/Ddp9Z4AdZWdGdoQy8re3BOcI0nVELUokuWnbOrjxDzASAb2nRSveJ84hxTGb30ZBDGUACaomgFGNkXhrVeKCj3G7iXr9tdHzfIOtjGkZYD7oXwB5suxvZJpf+LTugXTmUqgrt3CSuUTMRSnwiObxLTxq9liR91+CHBzeZvjAb+1+XFQOP40eqU4rRuqV43tAg8PFAUC6GgpjBokJ7W6VwIgn8LQfwPUbPHu6sgbzaRPzobKYMCcENN659EkiMgo5T2F4hS9g/QZp+STbumHoL+djGwOR62g2+EzA9XixwjVLjoJRf6pJ5T93lETUfmJIauWxKyAr06W8/1Sx6/AX4wTXzhZSJiOAoolaZw8MV1gdwUnggyhr4ELRrQBly0sD0D2Ef9RxtOvR3dAUgS8SVlMKKAwGPJ1XJqkK5HJdxnnZlIWFWa9MdLtNTyOt3hbe0DNw3cjk0oYFEcV/42qpyc+YmHW8tqzD01nC0SImo4wJFm18WrRRFCYU=
    - secure: w41RXPAd6hDgnxMvs6QTMmpcQzwV3f0pUD50LjwksGisUam9vrdQlBBAYjhegKdximjoSptLJ2Kw8vu9kIiD59q/TPrCDUrHyYq/uA4/YBOgVSv1Qo3tx4g5DAgShhEFvRNVK5D8Gw3wWbSlagHsRr7Ba+LHNv9a9jCq97k80NqHIlB4iALOhDxuOWnuFx5ffKBJdzFkLzysVjbmv5uBeJbveP5/b/Rz3legpPVqiqqATkG6UWobDoWnw4oR270SFVtvb67jy+PokNQNUDWt7HGh9hvT3gamW5xGXrfbK9mVxrvExQDaGT5QvV7KUdOqrXNjQissTTvZN3P2emq7QAIX+IsIuUi9FbKNWosi6rdo/sDE1WJEEdDA0a4+4dR6Il+xUk36YRoO6b9auSo/PZ2PNz1EeTc1OdoxI3fVc2triSEFE6pd/RV85gq1FvH2/1jvKQm1xw3CSLpO+kxWHQqw0NdYm1ZX/LufStKRc0n0PLeAAk/7OJsVpwwsGCkCCf/o+aLGo+Ge+GY1SfIhogoHnYjs7hZeQyYM8cGRhVNnUApw5hh1rDOdcAsT8b1Jb95mhacPmgyUc7ww7kBkCtvY5Bq/iZM/FiVg4HBVVJ+Il+5oxamquzMlnYBOeHgNkawVv0Lf5k1A4DLfZ6QWjut4N5DED+eHwq1HT51Vq/c=

script:
  - rm -rf $TRAVIS_BUILD_DIR/build
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: scp -r $TRAVIS_BUILD_DIR/build/* ${SSH_USER}@${SSH_HOST}:/${DEPLOY_DIR}
  on:
    branch: master
  local_dir: build
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_63cbc52e9149_key -iv $encrypted_63cbc52e9149_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_rsa
  - ssh-add .travis/deploy_rsa
  - echo -e "Host ${SSH_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
