language: node_js
node_js:
- node
cache: npm
env:
  global:
  - secure: lExddVhI1KtgxGLv4y0xyIY8PrevR3cxqw692dHnJdpyo9PslvpB1IQkn7WYazkZRdzbHbQ0a7XmvIyQFzdcBHiku+RHRnQEaZOIPYUYII00Z/qaE5osvqzAFAbfJuI9bNMj29/7Ic6i8YEZxGKjwnzNbJORV76IwcKkKxH1z8SO0XXlGvIadCo8p92TuIqV0GZgF8CtkMSy3m7wvZhgiqx7sBT2jrYG0d7cxjJ4e+BbI+zcO02Yy+uRIJJK/QmJPuZ+fTscYd5dRTQ7ro/LXJl3El456JzbZ7v7p7bdFBT6dq7vhUi5bJXKM33hHPNYeFE15BA+AqZ4uQhwtl7LSfBaMumzAgXv0GWq5Bd4IhNOwww3cFeDabF3AmtqfoLpN30AvMYI0wLTDD/xHWJvM4EUA/5TdgWR3V/Q9mctzQRBPbh2+YZ9cnpDwJlaeMueP7W1j/4lIDhM7JUFfLTG4vimrU5Px6AyRMhkIUG6Qb7egtbHEqhFJcftOGe4GCm5j27wA/bzZFLjbJnEQNkX4B5hzkxOJAAR72dsxUIFyl4gpHsAB9tSPhQiwKRFbblIJfT+eJzeBcOhuf7oixcIXpQ4a+tLmtnropLTGemfCdgO72o4DUWq4gFz2dYMPDiZoFQKt2omeAW0E/l8GLaM1k40C5nuUdt5QD926pohI90=
  - secure: ZQRubJpzIldTi8eGq98w93qBO4I9ukVStmOItNKxXQeeyoGb50Fx3r7XGu9YZTUdoEVyTNM8C3pOXJBAvs5li+rbnTrWHHVmtAirXBTasMW6iuZuyUhq/PKP8CufFB6cNZl3KRX3c1w5r3sfqTJ3TSN90JU0BR7OKHWVHrKVt8b/H9lIlf88bcT/RJK6KxJCAsO/LPdlhneVw8G3XiBEDYWTxlpFpYtZ1jz9nrxdjTecajvECn1JYx9YBHXbm1uG+Vg3JZpHizw6f+rWnALa5qLTEOQ9c28ELxh748X3MU++beAe7t8DWgAgx5dX9UDMU3ZndbIpGLI788cngRrsErhP7p+7DjWB8djfuYcQznJKoJxXi5CxpBQm8afOgDy+/w1PTWAQVHu5ORftj29fdO/SsxB62dQNUbMsM63Tk72l7Z2bc0sm0Fg2Z97KfU6yRYb3cRa1vkLGxocqlV2h7SPWl0DECqG5uHbI+bm1QcL0dD2w0o65IJUrqU5n2X4ga2+rCP9drgFqCl6pItzmW/QYXU+OgiH7expolILFz1pDWkf48w1ShleqTt+NiZs7fargjfJmWu1/CtCAVW29cuFJr3HSuGT/EDUdPk5NmBugGoliXGTTrlYxZmxgmFITbWFAY+7aMp6pBNuoJNY8hsAiILsmBp3B2pPSyuD6lZc=
  - secure: fzac66Hs1qP9pAa1ZN+NGlJaJtyWMK/Mu8PMjheONVAH5XlbVkhpfHbOFPy8huEkqP/57mT+zhvVR+7EQqaCplJe2QLRLiLpjthANLk6l1AbGvv3G/8J3rwLiPWOjMjG/KpgyqZHqhMSy+WDsPR/EQXsnb7QQgj+UHvkl9WabHrRSYCy7PHr0Z1dJoyfjAJnkZjaGNvRx8DW9E5ICIpUhZjzgJemClRqYRhoRfSl6d82PaUVnGNgdcjSQxVEjHq/ZqWdVLeohnNHK2orFi8cFhtxLUbDJZpPOtlQ4ZlZ5YoenJHttlK8d2+LmakNVZI0tgfRl4kTmY1Z14kVBg9BQ3uUv3xtNAVULalqyBrRlnPA//RDgNZJMo0yMMLhk98DAAWurYIoxHibISXp4VsuEJ9MOkH55cuPzjMJffpAPFDvwC+MrzYf8Dn9lzdjQXbU5159i86rwgUIiSCBgc4FobIEiEq2yw8d5KA/irIcZDGKwXouHoD6+S1xrzQA9c3DEWKvIgyg2B+F7vvF9sw80hR+pyovqaa2Sm7S7U+EyXitdelgK0QQdj9P3+OVREyrQpE05NRbCm8iKHKac03nKZ1KY900fEXJX8Pnt6M00BYbz/wGIWsjSZ8nzgnlbYwGzy2GEit/lTAyQgn3YhTjnLYdawlMilM68a+hP/M0fLc=
script:
- rm -rf $TRAVIS_BUILD_DIR/build
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: scp -r $TRAVIS_BUILD_DIR/build/* ${SSH_USER}@${SSH_HOST}:/${DEPLOY_DIR}
  on:
    branch: master
  local_dir: build
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_63cbc52e9149_key -iv $encrypted_63cbc52e9149_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_rsa
- ssh-add .travis/deploy_rsa
- echo -e "Host ${SSH_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
